language: ruby
os: linux
rvm: 2.0.0
sudo: required
dist: trusty

script:
  - gem install rubocop
  - rubocop
  - ./install --force-curl
  - ./uninstall -f
  - ./install
  - ~/.linuxbrew/bin/brew install ack
  - ./uninstall -f
